services:
  api:
    build:
      context: .
      dockerfile: containers/app.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/src:ro
    command: uvicorn src.app.main:app --proxy-headers --host 0.0.0.0 --port 80
